defaults:
  - _self_
  - logger: base_logger
  - arch: anakin
  - system: q_learning/rec_iql
  - network: rnn  # [rnn, rcnn]
  - env: smax  # [cleaner, connector, gigastep, lbf, matrax, rware, smax]

hydra:
  searchpath:
    - file://mava/configs
