site_name: Mava docs
site_description: Mava
site_author: Mava Contributors
repo_name: instadeep/Mava
repo_url: https://github.com/instadeepai/Mava
strict: false

theme:
  name: "material"
  language: en
  palette:
    primary: red
    accent: teal
  font:
    text: Avenir Next
  features:
    - navigation.tracking

plugins:
  - search
  - git-revision-date
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true

markdown_extensions:
  - pymdownx.snippets:
      base_path: ./

  - pymdownx.pathconverter:
      base_path: ./
      relative_path: docs

nav:
  - Home: index.md
  - Getting started:
      - General: getting_started/overview.md
      - The store: getting_started/store.md
      - The config: getting_started/config.md
      - Creating a system: getting_started/create_system.md
      - Creating a new component: getting_started/create_component.md
  - Systems:
      - General: systems/general.md
      - Jax:
          - ippo: systems/jax/ippo.md
  - Components:
      - General: components/components.md
      - Core Components: components/core_components.md
      - Build Components: components/build_components.md
      - Training Components: components/train_components.md
      - Executing Components: components/executing_components.md
      - Updating Components: components/updating_components.md
  - Environments:
      - General: environments/general.md
      - Supported Environments:
          - Debugging Environment: environments/debugging.md
          - PettingZoo: environments/pettingzoo.md
          - SMAC: environments/smac.md
          - Flatland: environments/flatland.md
          - Robocup: environments/robocup.md
          - Melting Pot: environments/meltingpot.md
          - Open Spiel: environments/open_spiel.md
  - Examples: examples.md
  - Gotchas: gotchas.md
  - Extra:
      - Troubleshooting and Frequently Asked Questions: TROUBLESHOOTING.md
      - How to add docs: add_doc.md
      - Annotation: annotation.md
