# The config of the 2s-8x8-2p-2f-coop scenario with the VectorObserver set as default.
name: LevelBasedForaging-v0
task_name: 2s-8x8-2p-2f-coop

task_config:
  grid_size: 8 # size of the grid to generate.
  fov: 2 # field of view of an agent.
  num_agents: 2 # number of agents on the grid.
  num_food: 2 # number of food in the environment.
  max_agent_level: 2 # maximum level of the agents (inclusive).
  force_coop: True # force cooperation between agents.

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
