# The config of the 10x10x5a scenario
name: MaConnector-v2
task_name: con-10x10x5a

task_config:
  grid_size: 10
  num_agents: 5

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
