defaults:
  - logger: ff_ippo
  - arch: anakin
  - system: ppo/ff_ippo
  - network: mlp  # [mlp, continuous_mlp, cnn]
  - env: acrobot  # [cleaner, connector, gigastep, lbf, mabrax, matrax, rware, smax]
  - _self_
