defaults:
  - logger: base_logger
  - arch: anakin
  - system: ppo/rec_mappo
  - network: rnn  # [rnn, rcnn]
  - env: rware  # [cleaner, connector, gigastep, lbf, mabrax, matrax, rware, smax]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
