name: format_and_test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ubuntu:
    runs-on: self-hosted
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [3.6.13, 3.7.1, 3.8.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          LC_ALL=C.UTF-8 pip install .
          LC_ALL=C.UTF-8 pip install .[tf,envs,reverb,testing_formatting,launchpad]
          # For atari envs
          sudo apt-get update
          sudo apt-get install unrar
          pip install autorom && echo y | AutoROM
          # Open CV
          sudo apt-get install ffmpeg libsm6 libxext6  -y
      - name: Format code
        run: |
          # Check code follows black formatting.
          black --check .
          # stop the build if there are Python syntax errors or undefined names
          flake8 .  --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --statistics
      - name: Check types with mypy
        run: |
          mypy . --exclude docs/
      - name: Test with pytest and get code coverage
        run: |
          pytest --cov-report term-missing --cov=mava  -n "$(grep -c ^processor /proc/cpuinfo)" tests
