name: format_and_test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-ubuntu:
    runs-on: onprem
    timeout-minutes: 45
    strategy:
      matrix:
        docker-image: ["python:3.7", "python:3.8", "python:3.9"]
    steps:
    - name: Checkout mava
      uses: actions/checkout@v2
    - name: Run tests in docker
      run: |
        docker run --mount "type=bind,src=$(pwd),dst=/tmp/mava" \
            -w "/tmp/mava" --rm ${{ matrix.docker-image }} /bin/bash bash_scripts/tests.sh
