# --- Logging options ---

use_tf: True # Whether to use tensorboard logging.
base_exp_path: results # Base path for logging.
use_json: True # Whether to log marl-eval style to json.

# --- Neptune logging ---
use_neptune: True

kwargs:
  neptune_project: Instadeep/Mava
  neptune_tag: [rware]
